update workflow

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -20,5 +20,15 @@ jobs:
         pip install -r requirements.txt -U
         pip install pylint
     - name: Analysing the code with pylint
+      id: pylint
       run: |
-        pylint $(git ls-files '*.py')
+        pylint $(git ls-files '*.py') | tee pylint_output.txt
+    - name: Check Pylint score
+      run: |
+        score=$(grep -oP '(?<=Your code has been rated at )\d+.\d+(?=\/10)' pylint_output.txt)
+        if (( $(echo "$score > 9" | bc -l) )); then
+          echo "Pylint score is $score. Success!"
+        else
+          echo "Pylint score is $score. Failed!"
+          exit 1
+        fi
